console.log("good morning, eveyone!.")
console.log("miran bae")
console.log("pasta", "chicken", "bread")
console.log("06301986")
console.log("38")
console.log("My name is miran and I am 38 years old.")
console.log("The current year is 2025. The next year will be 2026.")